=== DataInMotion/org.eclipse.sensinact.gateway/legacy/platform/sensinact-common/src/main/resources/frame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/*********************************************************************
* Copyright (c) 2021 Kentyou and others
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
-->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://org.eclipse.sensinact/frame"
xmlns:sensinact="http://org.eclipse.sensinact/frame" elementFormDefault="qualified">
	
	<simpleType name="delimitationType">
		<restriction base="unsignedInt">
			<enumeration id="START_DELIMITED" value="0"/>
			<enumeration id="END_DELIMITED" value="1"/>
			<enumeration id="START_END_DELIMITED" value="2"/>
			<enumeration id="SIZE_DELIMITED" value="3" />
			<enumeration id="SIZE_START_DELIMITED" value="4"/>
			<enumeration id="SIZE_END_DELIMITED" value="5"/>
			<enumeration id="SIZE_START_END_DELIMITED" value="6"/>
			<enumeration id="EMPTY_BUFFER_DELIMITED" value="7"/>
		</restriction>
	</simpleType>

	<complexType name="definitionType">
	   <sequence>	
	   		<element name="name" type="QName" maxOccurs="1" minOccurs="1" />
	   		<element name="implementation" type="QName" maxOccurs="1" minOccurs="1" />
	   		<element name="length" type="int" maxOccurs="1" minOccurs="0" /> 
	   </sequence>
    </complexType>
        
	<complexType name="frame">
		<sequence maxOccurs="1" minOccurs="1">
			<element name="frame" type="sensinact:frame" maxOccurs="unbounded" minOccurs="0"/>
		</sequence>
		<attribute name="name" use="required" type="QName" />
		<attribute name="offset" use="required" type="unsignedInt" />
    </complexType>
    
    <complexType name="definitionsType">
	   <sequence maxOccurs="unbounded" minOccurs="0">	
	   		<element name="type" type="sensinact:definitionType"/>
	   </sequence>
    </complexType>    
    
    <complexType name="frames">
    	<sequence minOccurs="1" maxOccurs="1">
    		<element name="types" type="sensinact:definitionsType" maxOccurs="1" minOccurs="1">    			
		   		<unique name="definitionKey">
	    			<selector xpath="sensinact:definition"/>
	    			<field xpath="sensinact:name"/>
	  			</unique>
    		</element>
    		<element name="frame" type="sensinact:frame" maxOccurs="1" minOccurs="1"/>
    	</sequence>	
	    <attribute name="delimiter" use="required" type="sensinact:delimitationType"/>
	    <attribute name="start" use="optional" type="byte"/>
	    <attribute name="end" use="optional" type="byte"/>
	    <attribute name="escape" use="optional" type="byte"/>
    </complexType>
    
    <element name="frames" type="sensinact:frames">	
	    <key name="frameName">
	      <selector xpath=".//sensinact:types/sensinact:type"/>
	      <field xpath="sensinact:name"/>
	    </key>
	    <keyref name="frameNameRef" refer="sensinact:frameName">
      		<selector xpath=".//sensinact:frame"/>
      		<field xpath="@name"/>
    	</keyref>
  	</element>
</schema>

=== DataInMotion/org.eclipse.sensinact.gateway/platform/sensinact-common/src/test/resources/frameTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Copyright (c) 2017 CEA.
  ~ All rights reserved. This program and the accompanying materials
  ~ are made available under the terms of the Eclipse Public License v1.0
  ~ which accompanies this distribution, and is available at
  ~ http://www.eclipse.org/legal/epl-v10.html
  ~
  ~ Contributors:
  ~    CEA - initial API and implementation
  -->

<sensinact:frames
 xmlns:sensinact="http://org.eclipse.sensinact/frame"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:schemaLocation="http://org.eclipse.sensinact/frame ../../main/resources/frame.xsd "
 delimiter="3">
  <sensinact:types>
  	<sensinact:type>
  		<sensinact:name>first</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.TFrame</sensinact:implementation>
  	</sensinact:type>
  	<sensinact:type>
  		<sensinact:name>second</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.TFrame_1</sensinact:implementation>
  		<sensinact:length>1</sensinact:length>
  	</sensinact:type>
  	<sensinact:type>
  		<sensinact:name>third</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.TFrame_2</sensinact:implementation>
  		<sensinact:length>3</sensinact:length>
  	</sensinact:type>
  	<sensinact:type>
  		<sensinact:name>fourth</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.TFrame_3</sensinact:implementation>
  		<sensinact:length>2</sensinact:length>
  	</sensinact:type>
  	<sensinact:type>
  		<sensinact:name>fifth</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.TFrame_4</sensinact:implementation>
  		<sensinact:length>1</sensinact:length>
  	</sensinact:type>
  </sensinact:types>
  <sensinact:frame name="first" offset="0">
  	<sensinact:frame name="third" offset="0"/>
  	<sensinact:frame name="fourth" offset="3">
  		<sensinact:frame name="fifth" offset="0"/>
  		<sensinact:frame name="second" offset="1"/>  		
  	</sensinact:frame>  	
  </sensinact:frame>
</sensinact:frames>

=== DataInMotion/org.eclipse.sensinact.gateway/legacy/platform/sensinact-common/src/test/resources/frameTest2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
/*********************************************************************
* Copyright (c) 2021 Kentyou and others
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
-->

<sensinact:frames
	delimiter="4" 
	start="-1" 
	escape="35"
	xmlns:sensinact="http://org.eclipse.sensinact/frame"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://org.eclipse.sensinact/frame ../../main/resources/frame.xsd ">
  <sensinact:types>
  	<sensinact:type>
  		<sensinact:name>parent</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.TFrame</sensinact:implementation>
  	</sensinact:type>
  	<sensinact:type>
  		<sensinact:name>parent_bis</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.TFrame_1</sensinact:implementation>
  	</sensinact:type>
  	<sensinact:type>
  		<sensinact:name>date</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.UnixEpoch</sensinact:implementation>
  		<sensinact:length>4</sensinact:length>
  	</sensinact:type>
  	<sensinact:type>
  		<sensinact:name>size</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.OneByteSizeFrame</sensinact:implementation>
  		<sensinact:length>1</sensinact:length>
  	</sensinact:type>
  	<sensinact:type>
  		<sensinact:name>data</sensinact:name>
  		<sensinact:implementation>org.eclipse.sensinact.gateway.common.automata.test.ASCIIDataFrame</sensinact:implementation>
  	</sensinact:type>
  </sensinact:types>
  <sensinact:frame name="parent" offset="0">
	<sensinact:frame name="size" offset="0"/>
	<sensinact:frame name="date" offset="1"/>
	<sensinact:frame name="parent_bis" offset="5">
		<sensinact:frame name="date" offset="0"/>
		<sensinact:frame name="data" offset="4"/>
	</sensinact:frame>
  </sensinact:frame>
</sensinact:frames>
